development:     #
  adapter: postgresql
  encoding: unicode
  database: likelion
  pool: 5
  username: likelion
  password: 123456789
  host: pgsql.likelion.com.br
  port: 5432

test:            #
  adapter: postgresql
  encoding: unicode
  database: ghotsite
  pool: 5
  username: postgres
  password: di03051999
  host: localhost 
  port: 5432

production:      #
  adapter: postgresql
  encoding: unicode
  database: likelion
  pool: 5
  username: likelion
  password: 123456789
  host: pgsql.likelion.com.br
  port: 5432
